name: build-image for shimboot
run-name: Build shimboot for octopus (Ubuntu)
on: [push]
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: remove snap
        uses: ading2210/gh-actions-remove-snap@v1
        with:
          disable_man_db: 'true'
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - name: download repo
        uses: actions/checkout@v4
      
      - name: run build
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo DEBUG=1 ./build_complete.sh octopus compress_img=1 quiet=1 distro=ubuntu release=noble mirror=https://archive.ubuntu.com/ubuntu
      - name: upload img
        uses: actions/upload-artifact@v4
        with:
          name: shimboot_octopus_ubuntu
          path: data/shimboot_octopus.bin
          compression-level: 7
  
      - name: create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: data/shimboot_octopus.zip
